/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalSlots' : IDL.Nat,
  'pdfKey' : IDL.Text,
  'entryFee' : IDL.Text,
  'filledSlots' : IDL.Nat,
  'rules' : IDL.Text,
  'prizePool' : IDL.Text,
  'format' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const UserProfile = IDL.Record({
  'teamName' : IDL.Text,
  'contact' : IDL.Text,
  'name' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'id' : IDL.Nat,
  'teamName' : IDL.Text,
  'rank' : IDL.Nat,
  'tournamentId' : IDL.Nat,
  'kills' : IDL.Nat,
  'points' : IDL.Nat,
});
export const Registration = IDL.Record({
  'id' : IDL.Nat,
  'playerIds' : IDL.Text,
  'teamName' : IDL.Text,
  'contact' : IDL.Text,
  'captainName' : IDL.Text,
  'registeredAt' : IDL.Int,
  'tournamentId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [Announcement], []),
  'createTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Tournament],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [Result], []),
  'deleteTournament' : IDL.Func([IDL.Nat], [Result], []),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlobalLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getRegistrations' : IDL.Func([IDL.Nat], [IDL.Vec(Registration)], []),
  'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
  'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerForTournament' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTournament' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Result],
      [],
    ),
  'upsertLeaderboardEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalSlots' : IDL.Nat,
    'pdfKey' : IDL.Text,
    'entryFee' : IDL.Text,
    'filledSlots' : IDL.Nat,
    'rules' : IDL.Text,
    'prizePool' : IDL.Text,
    'format' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const UserProfile = IDL.Record({
    'teamName' : IDL.Text,
    'contact' : IDL.Text,
    'name' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'id' : IDL.Nat,
    'teamName' : IDL.Text,
    'rank' : IDL.Nat,
    'tournamentId' : IDL.Nat,
    'kills' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const Registration = IDL.Record({
    'id' : IDL.Nat,
    'playerIds' : IDL.Text,
    'teamName' : IDL.Text,
    'contact' : IDL.Text,
    'captainName' : IDL.Text,
    'registeredAt' : IDL.Int,
    'tournamentId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [Announcement], []),
    'createTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Tournament],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [Result], []),
    'deleteTournament' : IDL.Func([IDL.Nat], [Result], []),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlobalLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getRegistrations' : IDL.Func([IDL.Nat], [IDL.Vec(Registration)], []),
    'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
    'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerForTournament' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTournament' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Result],
        [],
      ),
    'upsertLeaderboardEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };