/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
}
export interface LeaderboardEntry {
  'id' : bigint,
  'teamName' : string,
  'rank' : bigint,
  'tournamentId' : bigint,
  'kills' : bigint,
  'points' : bigint,
}
export interface Registration {
  'id' : bigint,
  'playerIds' : string,
  'teamName' : string,
  'contact' : string,
  'captainName' : string,
  'registeredAt' : bigint,
  'tournamentId' : bigint,
}
export type Result = { 'ok' : string } |
  { 'err' : string };
export interface Tournament {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'date' : string,
  'createdAt' : bigint,
  'totalSlots' : bigint,
  'pdfKey' : string,
  'entryFee' : string,
  'filledSlots' : bigint,
  'rules' : string,
  'prizePool' : string,
  'format' : string,
}
export interface UserProfile {
  'teamName' : string,
  'contact' : string,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<[string, string], Announcement>,
  'createTournament' : ActorMethod<
    [string, string, string, bigint, string, string, string, string, string],
    Tournament
  >,
  'deleteAnnouncement' : ActorMethod<[bigint], Result>,
  'deleteTournament' : ActorMethod<[bigint], Result>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGlobalLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getLeaderboard' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getRegistrations' : ActorMethod<[bigint], Array<Registration>>,
  'getTournament' : ActorMethod<[bigint], [] | [Tournament]>,
  'getTournaments' : ActorMethod<[], Array<Tournament>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerForTournament' : ActorMethod<
    [bigint, string, string, string, string],
    Result
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTournament' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
    ],
    Result
  >,
  'upsertLeaderboardEntry' : ActorMethod<
    [bigint, bigint, string, bigint, bigint],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];